/** Collection of short, humorous, non-tech slogans for ogur.dev. */
export const SLOGANS: string[] = [
  'Robię ogur.dev, żeby wreszcie ogarnąć autoryzację i API, bo ile można żyć na apikey=1234 w URL jak jakiś dzban.🥒',
  'ogur.dev – bo każdy z nas miał ten moment, gdy token JWT trzymał w notatniku na pulpicie obok ‘hasła_do_netflixa.txt’.🥒',
  'API key w query stringu? Nie, dzięki. ogur.dev to mój detox po latach bycia programistycznym menelem.🥒',
  'ogur.dev – jak chcesz być seniorem, ale wciąż używasz if(user == admin) do autoryzacji.🥒',
  "Kiedy masz dość kopiowania curl -H 'Authorization: Bearer …' z notatnika – wchodzi ogur.dev cały na zielono.🥒",
  'ogur.dev: bo jak jeszcze raz zobaczę API zabezpieczone hasłem ‘qwerty123’, to zwinę produkcję i wyjadę w Bieszczady.🥒',
  'TU MIAŁEM COŚ NAPISAĆ ALE WYJEBANE XDDDD🥒',
  'Firma same legendy🥒',
  'Firma same legendy🥒',
  '67 mango musztarda🥒',
  '67 mango musztarda🥒',
  'ogur.dev – robię stronki tak samo soczyste jak ogórek małosolny.🥒',
  'ogur.dev – robię stronki tak samo soczyste jak ogórek małosolny.🥒',
  'To nie jest kolejny sklep z ogórkami. To jest ten ogur.dev.🥒',
  'To nie jest kolejny sklep z ogórkami. To jest ten ogur.dev.🥒',
  'Jak nie wiesz co to jest API – spoko, ja też udaję, że wiem. ogur.dev.🥒',
  'Jak nie wiesz co to jest API – spoko, ja też udaję, że wiem. ogur.dev.🥒',
  'ogur.dev – moja strona, twój problem.🥒',
  'ogur.dev – moja strona, twój problem.🥒',
  'Powiedzmy tak: inni budują startupy, a ja buduję ogura. ogur.dev🥒',
  'Powiedzmy tak: inni budują startupy, a ja buduję ogura. ogur.dev🥒',
  'Strona tak świeża, że aż pachnie koperkiem.🥒',
  'Strona tak świeża, że aż pachnie koperkiem.🥒',
];
