#!/usr/bin/env node
/**
 * Generate i18n locales from /src/messages/*.json
 * Produces: src/i18n/locales.generated.ts
 */
import fs from 'fs';
import path from 'path';

const ROOT = process.cwd();
const MSG_DIR = path.join(ROOT, 'src', 'messages');
const OUT_DIR = path.join(ROOT, 'src', 'i18n');
const OUT_FILE = path.join(OUT_DIR, 'locales.generated.ts');

type Meta = { label?: string; flag?: string; default?: boolean };

function readJson(p: string) {
    const raw = fs.readFileSync(p, 'utf-8');
    return JSON.parse(raw) as { meta?: Meta };
}

function main() {
    if (!fs.existsSync(MSG_DIR)) {
        console.error(`[i18n] Not found: ${MSG_DIR}`);
        process.exit(1);
    }
    const files = fs.readdirSync(MSG_DIR).filter(f => f.endsWith('.json'));
    if (files.length === 0) {
        console.error('[i18n] No message json files found.');
        process.exit(1);
    }

    const entries: { code: string; meta: Meta }[] = [];
    for (const f of files) {
        const code = path.basename(f, '.json'); // en.json -> en
        const j = readJson(path.join(MSG_DIR, f));
        const meta: Meta = j.meta ?? {};
        entries.push({ code, meta });
    }

    // default locale detection
    const defaults = entries.filter(e => !!e.meta.default);
    if (defaults.length > 1) {
        console.error('[i18n] Multiple locales marked as default:', defaults.map(d => d.code));
        process.exit(1);
    }
    const defaultLocale = (defaults[0]?.code) ?? entries[0].code;

    // generate TS
    const locales = entries.map(e => e.code);
    const metaMap: Record<string, {label: string; flag: string}> = {};
    for (const e of entries) {
        metaMap[e.code] = {
            label: e.meta.label ?? e.code,
            flag: e.meta.flag ?? e.code
        };
    }

    if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

    const content = `/* AUTO-GENERATED by scripts/gen-locales.ts – DO NOT EDIT */
export const locales = ${JSON.stringify(locales)} as const;
export type Locale = typeof locales[number];
export const defaultLocale: Locale = ${JSON.stringify(defaultLocale)} as Locale;

export const localeMeta: Record<Locale, {label: string; flag: string}> = ${JSON.stringify(metaMap, null, 2)} as any;

export function isLocale(x: string): x is Locale {
  return (locales as readonly string[]).includes(x);
}
`;
    fs.writeFileSync(OUT_FILE, content, 'utf-8');
    console.log(`[i18n] Generated: ${path.relative(ROOT, OUT_FILE)} (${locales.length} locales, default=${defaultLocale})`);
}

main();
