/* AUTO-GENERATED by scripts/gen-locales.ts – DO NOT EDIT */
export const locales = ["pl","en","de","da","fr","cz","it","nl","no","fi","sv","ja","es","ko","pt","ru","ua","zh"] as const;
export type Locale = typeof locales[number];
export const defaultLocale: Locale = "en" as Locale;

export const enabledLocales = ["pl","en","de","da","fr","cz","it","nl","no","fi","sv","ja"] as const;
export type EnabledLocale = typeof enabledLocales[number];


export const localeMeta: Record<Locale, {label: string; flag: string}> = {
  "cz": {
    "label": "Čeština",
    "flag": "cz"
  },
  "da": {
    "label": "Dansk",
    "flag": "dk"
  },
  "de": {
    "label": "Deutsch",
    "flag": "de"
  },
  "en": {
    "label": "English",
    "flag": "gb"
  },
  "es": {
    "label": "Español",
    "flag": "es"
  },
  "fi": {
    "label": "Suomi",
    "flag": "fi"
  },
  "fr": {
    "label": "Français",
    "flag": "fr"
  },
  "it": {
    "label": "Italiano",
    "flag": "it"
  },
  "ja": {
    "label": "日本語",
    "flag": "jp"
  },
  "ko": {
    "label": "한국어",
    "flag": "kr"
  },
  "nl": {
    "label": "Nederlands",
    "flag": "nl"
  },
  "no": {
    "label": "Norsk",
    "flag": "no"
  },
  "pl": {
    "label": "Polski",
    "flag": "pl"
  },
  "pt": {
    "label": "Português",
    "flag": "pt"
  },
  "ru": {
    "label": "Русский",
    "flag": "ru"
  },
  "sv": {
    "label": "Svenska",
    "flag": "se"
  },
  "ua": {
    "label": "Українська",
    "flag": "ua"
  },
  "zh": {
    "label": "简体中文",
    "flag": "cn"
  }
} as any;

export function isLocale(x: string): x is Locale {
  return (locales as readonly string[]).includes(x);
}
