/* AUTO-GENERATED by scripts/gen-locales.ts – DO NOT EDIT */
export const locales = ["pl","en","de","da","cz","es","fr","it","nl","no","pt","sv","ua"] as const;
export type Locale = typeof locales[number];
export const defaultLocale: Locale = "en" as Locale;

export const enabledLocales = ["pl","en","de","da"] as const;
export type EnabledLocale = typeof enabledLocales[number];

export const localeMeta: Record<Locale, {label: string; flag: string}> = {
  "cz": {
    "label": "Čeština",
    "flag": "cz"
  },
  "da": {
    "label": "Dansk",
    "flag": "dk"
  },
  "de": {
    "label": "Deutsch",
    "flag": "de"
  },
  "en": {
    "label": "English",
    "flag": "gb"
  },
  "es": {
    "label": "Español",
    "flag": "es"
  },
  "fr": {
    "label": "Français",
    "flag": "fr"
  },
  "it": {
    "label": "Italiano",
    "flag": "it"
  },
  "nl": {
    "label": "Nederlands",
    "flag": "nl"
  },
  "no": {
    "label": "Norsk",
    "flag": "no"
  },
  "pl": {
    "label": "Polski",
    "flag": "pl"
  },
  "pt": {
    "label": "Português",
    "flag": "pt"
  },
  "sv": {
    "label": "Svenska",
    "flag": "se"
  },
  "ua": {
    "label": "Українська",
    "flag": "ua"
  }
} as any;

export function isLocale(x: string): x is Locale {
  return (locales as readonly string[]).includes(x);
}
